title: StorRAG
description: A RAG Appliance, to turn "your" storage, into "your" data.
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
url: "https://storrag.github.io"
baseurl: "/storrag" 
